[package]
name = "workanda"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
web = "0.2.12"
oauth2 = "5.0.0"
totp-rs = "5.0"
base32 = "0.5.1"
aes-gcm = "0.10.3"
rpassword = "7"
jsonwebtoken = "9.3.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4" # For handling timestamps
dotenv = "0.15" # To load environment variables (optional)
rdkafka = { version = "0.37.0", features = ["tokio"] }