use sqlx::PgPool;
use sqlx::Error;
use crate::models::{EscrowAccount, EscrowStatus,  MembershipTier, PaymentHistory};
use log::{info, error};
use rust_decimal::Decimal;
use std::convert::TryFrom;
use uuid::Uuid;

// Function to create escrow account
pub async fn create_escrow_account(
    pool: &PgPool,
    contract_id: Uuid,
    amount: Decimal,
) -> Result<EscrowAccount, sqlx::Error> {
    let new_escrow = EscrowAccount {
        id: 0,
        contract_id,
        amount,
        status: EscrowStatus::Pending,
        dispute: None,
    };

    info!("Creating escrow account for contract_id: {} with amount: {}", contract_id, amount);

    let result = sqlx::query_as!(
        EscrowAccount,
        r#"
        INSERT INTO escrow_accounts (contract_id, amount, status)
        VALUES ($1, $2, $3)
        RETURNING id, contract_id, amount, status, dispute
        "#,
        contract_id,
        amount,
        new_escrow.status as EscrowStatus
    )
    .fetch_one(pool)
    .await;

    match result {
        Ok(escrow_account) => {
            info!("Escrow account created with ID: {}", escrow_account.id);
            Ok(escrow_account)
        },
        Err(e) => {
            error!("Failed to create escrow account: {:?}", e);
            Err(e)
        }
    }
}


// Function to create contract with escrow
pub async fn create_contract_with_escrow(
    pool: &PgPool,
    contract: &Contract,
    escrow_amount: Decimal,
) -> Result<(Contract, EscrowAccount), Error> {

    ensure_account_exists(pool, contract.client_id, "CLIENT").await?;
    ensure_account_exists(pool, contract.freelancer_id, "FREELANCER").await?;

    // Insert the contract
    let new_contract = sqlx::query_as!(
        Contract,
        r#"
        INSERT INTO contracts (field1, field2, ...)  -- Replace with actual fields
        VALUES ($1, $2, ...)  -- Replace with actual values
        RETURNING id, field1, field2, ...
        "#,
        contract.field1, contract.field2 // Use the actual contract fields
    )
    .fetch_one(pool)
    .await?;

    // Create the escrow account
    let escrow_account = EscrowAccount {
        id: 0, // This will be generated by the database
        contract_id: new_contract.id,
        amount: escrow_amount,
        status: EscrowStatus::Pending,
        dispute: None,
    };

    let new_escrow_account = sqlx::query_as!(
        EscrowAccount,
        r#"
        INSERT INTO escrow_accounts (contract_id, amount, status, dispute)
        VALUES ($1, $2, $3, $4)
        RETURNING id, contract_id, amount, status, dispute
        "#,
        escrow_account.contract_id,
        escrow_account.amount,
        escrow_account.status as _,
        escrow_account.dispute as _
    )
    .fetch_one(pool)
    .await?;

    Ok((new_contract, new_escrow_account))
}

// Function to lock funds in the escrow account
pub async fn lock_funds_in_escrow(
    pool: &PgPool,
    contract_id: Uuid,
    amount: Decimal,
) -> Result<(), String> {
    let mut transaction = pool.begin().await.map_error(|e| e.to_string())?;

    // Fetch the escrow account by contract_id
    let mut escrow_account = sqlx::query_as!(
        EscrowAccount,
        r#"
        SELECT id, contract_id, amount, status, dispute
        FROM escrow_accounts
        WHERE contract_id = $1
        "#,
        contract_id
    )
    .fetch_one(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    if escrow_account.status != EscrowStatus::Pending {
        return Err("Cannot lock funds for non-pending escrow".into());
    }

        // Update the escrow balance
    let updated_balance = escrow_account.amount.checked_add(amount)
        .ok_or("Decimal overflow on fund locking".into())?;


    let update_result = sqlx::query!(
        r#"
        UPDATE escrow_accounts
        SET amount = $1
        WHERE contract_id = $2
        "#,
        updated_balance,
        contract_id
    )
    .execute(&mut *transaction)
    .await;

    update_result
        .map_err(|e| e.to_string())?;

    // Record the payment history
    let _ = sqlx::query!(
        r#"
        INSERT INTO payment_history (escrow_account_id, amount, transaction_type)
        VALUES ($1, $2, 'Fund Lock')
        "#,
        escrow_account.id,
        amount,
        "Deposit"
    )
    .execute(pool)
    .await
    .map_err(|e| e.to_string())?;

    transaction.commit().await.map_err(|e| e.to_string())
}

#[derive(Debug, PartialEq, Eq)]
pub enum EscrowStatus {
    LOCKED,
    AUTHORIZED,
    RELEASED,
}

impl ToString for EscrowStatus {
    fn to_string(&self) -> String {
        match self {
            EscrowStatus::LOCKED => "LOCKED".to_string(),
            EscrowStatus::AUTHORIZED => "AUTHORIZED".to_string(),
            EscrowStatus::RELEASED => "RELEASED".to_string(),
        }
    }
}


//Function to release escrow funds innit,i need a break gaddamn
pub async fn release_escrow_funds(
    pool: &PgPool,
    contract_id: Uuid,
    amount: Decimal,
    is_partial: bool,
) -> Result<(), String> {
    let mut transaction = pool.begin().await.map_err(|e| e.to_string())?;

    // Fetch contract details to get client and freelancer IDs
    let contract = sqlx::query_as!(
        Contract,
        r#"
        SELECT client_id, freelancer_id
        FROM contracts
        WHERE id = $1
        "#,
        contract_id
    )
    .fetch_one(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    // Fetch escrow account details
    let mut escrow_account = sqlx::query_as!(
        EscrowAccount,
        r#"
        SELECT id, contract_id, amount, status, dispute, release_status
        FROM escrow_accounts
        WHERE contract_id = $1
        "#,
        contract_id
    )
    .fetch_one(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    // Check for pending dispute
    if escrow_account.dispute {
        return Err("Escrow has a pending dispute. Release cannot proceed.".to_string());
    }

    // Ensure release is authorized
    let release_status: EscrowStatus = escrow_account.release_status.parse().unwrap_or(EscrowStatus::LOCKED);
    if release_status != EscrowStatus::AUTHORIZED {
        return Err("Release not authorized by the client.".to_string());
    }

    if let Some(amount) = amount {
        // Calculate fee and total release amount
        let fee = calculate_fee(amount, MembershipTier::Normal).min(1000.0);
        let total_release = amount.checked_add(fee)
        .ok_or("Amount overflow".into())?;

        // Check sufficient funds
        if escrow_account.amount < total_release {
            return Err("Insufficient funds to cover amount and fee.".to_string());
        }

        // Deduct total from escrow and update status to 'RELEASED'

        escrow_account.amount -= total_release;

        sqlx::query!(
            r#"
            UPDATE escrow_accounts
            SET amount = amount - $1,
                release_status = $2
            WHERE contract_id = $3
            "#,
            total_release,
            escrow_account.amount
            EscrowStatus::RELEASED.to_string(),
            contract_id
        )
        .execute(&mut *transaction)
        .await
        .map_err(|e| e.to_string())?;

        // Transfer amount to freelancer's account
        sqlx::query!(
            r#"
            UPDATE accounts
            SET balance = balance + $1
            WHERE id = $2
            "#,
            amount,
            contract.freelancer_id
        )
        .execute(&mut *transaction)
        .await
        .map_err(|e| e.to_string())?;

        update_balance(&mut *transaction, contract.freelancer_id, amount).await?;
        update_balance(&mut *transaction, PLATFORM_ACCOUNT_ID, fee).await?;
    
     // Transfer fee to platform's account (assuming platform ID is 1)
        const PLATFORM_ACCOUNT_ID: i32 = 1;
        record_payment_history(
            &mut *transaction,
            escrow_account.id,
            amount,
            if is_partial { "Partial Release" } else { "Full Release" },
        ).await?;
    
        record_payment_history(
            &mut *transaction,
            escrow_account.id,
            fee,
            "Platform Fee",
        ).await?;
    
        transaction.commit().await.map_err(|e| e.to_string());

        // Notify the freelancer that funds have been released
        notify_freelancer_of_release(contract.freelancer_id, amount, is_partial).await?;
    }

    transaction.commit().await.map_err(|e| e.to_string())
}

// Helper function to notify the freelancer
async fn notify_freelancer_of_release(freelancer_id: i32, amount: Decimal, is_partial: bool) -> Result<(), String> {
    let notification_message = if is_partial {
        format!("A partial payment of ${:.2} has been released to your account.", amount)
    } else {
        format!("The full payment of ${:.2} has been released to your account.", amount)
    };

    sqlx::query!(
        r#"
        INSERT INTO notifications (user_id, message, type)
        VALUES ($1, $2, $3)
        "#,
        freelancer_id,
        notification_message,
        "Payment Released"
    )
    .execute(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    transaction.commit().await.map_err(|e| e.to_string())
}

// Function to calculate the fee (this is just a placeholder, you can implement your logic here)
fn calculate_fee(amount: Decimal, tier: MembershipTier) -> f64 {
    match tier {
        MembershipTier::Normal => amount * 0.05, // Example: 5% fee for normal members
        MembershipTier::Premium => amount * 0.02, // Example: 2% fee for premium members
    }
}

pub async fn process_refund(
    pool: &PgPool,
    contract_id: Uuid,
    amount: Decimal,
    reason: String,
    refund_type: RefundType,
) -> Result<RefundResult, String> {
    let mut transaction = pool.begin().await.map_err(|e| e.to_string())?;

    // Fetch contract details to get client ID
    let contract = sqlx::query_as!(
        Contract,
        r#"
        SELECT client_id, freelancer_id, total_amount
        FROM contracts
        WHERE id = $1
        "#,
        contract_id
    )
    .fetch_one(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    // Fetch escrow account details
    let escrow_account = sqlx::query!(
        r#"
        SELECT id, contract_id, amount, status, dispute
        FROM escrow_accounts
        WHERE contract_id = $1
        "#,
        contract_id
    )
    .fetch_one(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    // Comprehensive validation
    if escrow_account.dispute {
        return Err("Cannot refund while a dispute is active. Please resolve the dispute first.".to_string());
    }
    
    if escrow_account.status != "LOCKED" && escrow_account.status != "RESOLVED" {
        return Err(format!("Escrow is not in a refundable state. Current status: {}", escrow_account.status));
    }

    // Validate refund amount
    if amount <= Decimal::ZERO {
        return Err("Refund amount must be greater than zero.".to_string());
    }

    // Validate sufficient funds
    if escrow_account.amount < amount {
        return Err(format!(
            "Insufficient funds to process refund. Available: {}, Requested: {}",
            escrow_account.amount, amount
        ));
    }

    // Calculate refund fee if applicable
    let refund_fee = match refund_type {
        RefundType::Full => Decimal::ZERO,
        RefundType::Partial => amount * Decimal::from_str("0.025").unwrap(), // 2.5% fee for partial refunds
        RefundType::Disputed => Decimal::ZERO, // No fee for dispute-resolved refunds
    };

    let net_refund_amount = amount - refund_fee;

    // Validate client account exists
    validate_account_exists(&mut *transaction, contract.client_id).await?;

    // Deduct from escrow
    let new_escrow_amount = escrow_account.amount - amount;
    sqlx::query!(
        r#"
        UPDATE escrow_accounts
        SET amount = $1,
            status = CASE 
                WHEN $1 = 0 THEN 'REFUNDED'
                ELSE status
            END
        WHERE contract_id = $2
        "#,
        new_escrow_amount,
        contract_id
    )
    .execute(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    // Transfer refunded amount to client's account
    update_balance(&mut *transaction, contract.client_id, net_refund_amount).await?;

    // Transfer fee to platform if applicable
    if refund_fee > Decimal::ZERO {
        const PLATFORM_ACCOUNT_ID: i32 = 1;
        update_balance(&mut *transaction, PLATFORM_ACCOUNT_ID, refund_fee).await?;
    }

    // Create refund record
    let refund_id = sqlx::query_scalar!(
        r#"
        INSERT INTO refunds (
            escrow_account_id,
            contract_id,
            amount,
            fee,
            net_amount,
            reason,
            refund_type,
            status,
            processed_at
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, 'completed', NOW())
        RETURNING id
        "#,
        escrow_account.id,
        contract_id,
        amount,
        refund_fee,
        net_refund_amount,
        reason,
        refund_type.to_string()
    )
    .fetch_one(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    // Record refund in payment history
    record_payment_history(
        &mut *transaction,
        escrow_account.id,
        amount,
        &format!("Refund - {}", refund_type.to_string()),
        contract.client_id,
    ).await?;

    // Send notifications
    send_refund_notification(
        &mut *transaction,
        contract.client_id,
        contract.freelancer_id,
        net_refund_amount,
        &reason
    ).await?;

    transaction.commit().await.map_err(|e| e.to_string())?;

    Ok(RefundResult {
        refund_id,
        amount,
        fee: refund_fee,
        net_amount: net_refund_amount,
        status: "completed".to_string(),
    })
}

#[derive(Debug)]
pub enum RefundType {
    Full,
    Partial,
    Disputed,
}

impl ToString for RefundType {
    fn to_string(&self) -> String {
        match self {
            RefundType::Full => "full".to_string(),
            RefundType::Partial => "partial".to_string(),
            RefundType::Disputed => "disputed".to_string(),
        }
    }
}

#[derive(Debug)]
pub struct RefundResult {
    pub refund_id: i32,
    pub amount: Decimal,
    pub fee: Decimal,
    pub net_amount: Decimal,
    pub status: String,
}

async fn send_refund_notification(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    client_id: i32,
    freelancer_id: i32,
    amount: Decimal,
    reason: &str,
) -> Result<(), String> {
    // Send notification to client
    sqlx::query!(
        r#"
        INSERT INTO notifications (user_id, type, title, message, created_at)
        VALUES ($1, 'refund', 'Refund Processed', $2, NOW())
        "#,
        client_id,
        format!("Your refund of ${} has been processed. Reason: {}", amount, reason)
    )
    .execute(&mut **transaction)
    .await
    .map_err(|e| e.to_string())?;

    // Send notification to freelancer
    sqlx::query!(
        r#"
        INSERT INTO notifications (user_id, type, title, message, created_at)
        VALUES ($1, 'refund', 'Refund Issued', $2, NOW())
        "#,
        freelancer_id,
        format!("A refund of ${} has been issued for the contract.", amount)
    )
    .execute(&mut **transaction)
    .await
    .map_err(|e| e.to_string())?;

    Ok(())
}

pub async fn get_escrow_account_details(
    pool: &PgPool,
    contract_id: Uuid,
) -> Result<EscrowDetails, String> {
    #[derive(Debug, sqlx::FromRow)]
    struct EscrowDetails {
        balance: Decimal,
        status: String,
        dispute: bool,
        payment_history: Vec<PaymentHistory>,
    }

    let escrow_details: EscrowDetails = sqlx::query_as!(
        EscrowDetails,
        r#"
        SELECT 
            e.amount AS balance,
            e.status,
            e.dispute,
            ph.amount,
            ph.transaction_type,
            ph.timestamp
        FROM escrow_accounts e
        LEFT JOIN payment_history ph ON e.id = ph.escrow_account_id
        WHERE e.contract_id = $1
        "#,
        contract_id
    )
    .fetch_all(pool)
    .await
    .map_err(|e| e.to_string())?
    .into_iter()
    .fold(
        EscrowDetails {
            balance: Decimal::default(),
            status: "".into(),
            dispute: false,
            payment_history: vec![],
        },
        |mut acc, row| {
            acc.balance = row.balance;
            acc.status = row.status;
            acc.dispute = row.dispute;
            acc.payment_history.push(PaymentHistory {
                amount: row.amount,
                transaction_type: row.transaction_type,
                timestamp: row.timestamp,
            });
            acc
        },
    );

    Ok(escrow_details)
}

// Function to charge a project fee
pub async fn charge_project_fee(
    pool: &PgPool,
    project_fee: ProjectFee,
) -> Result<(), String> {
    // Validate fee amount
    if project_fee.amount <= 0.0 {
        error!("Invalid fee amount: {}", project_fee.amount);
        return Err("Fee amount must be greater than zero.".to_string());
    }

    // Implement fee charging logic here (e.g., Stripe or another payment gateway)
    // Simulate fee charging (replace with actual gateway call)
    let fee_charged = true; // Replace with actual result from payment gateway

    if fee_charged {
        info!(
            "Successfully charged fee_amount: {} for contract_id: {} (FeeType: {:?})",
            project_fee.amount, project_fee.contract_id, project_fee.fee_type
        );

        // Optionally update charged_at timestamp
        sqlx::query!(
            r#"
            UPDATE project_fees
            SET charged_at = $1
            WHERE id = $2
            "#,
            Some(Utc::now()),
            project_fee.id
        )
        .execute(pool)
        .await
        .map_err(|e| e.to_string())?;

        Ok(())
    } else {
        error!(
            "Failed to charge fee_amount: {} for contract_id: {} (FeeType: {:?})",
            project_fee.amount, project_fee.contract_id, project_fee.fee_type
        );
        Err("Failed to charge project fee.".to_string())
    }
}


pub async fn escalate_dispute(
    pool: &PgPool,
    dispute_id: Uuid,
) -> Result<(), Error> {
    use crate::schema::disputes::dsl::*;

    info!("Escalating dispute_id: {}", dispute_id);

    let current_level: DisputeLevel = sqlx::query!(
        r#"
        SELECT level FROM disputes WHERE id = $1
        "#,
        dispute_id
    )
    .fetch_one(pool)
    .await?
    .level;

    let next_level = match current_level {
        DisputeLevel::InitialReview => DisputeLevel::Mediation,
        DisputeLevel::Mediation => DisputeLevel::Arbitration,
        DisputeLevel::Arbitration => DisputeLevel::Resolved,
        _ => return Err(Error::RowNotFound),
    };

    info!("Dispute level escalated from {:?} to {:?}", current_level, next_level);

    sqlx::query!(
        r#"
        UPDATE disputes SET level = $1 WHERE id = $2
        "#,
        next_level as i32,
        dispute_id
    )
    .execute(pool)
    .await?;

    Ok(())
}
//the escrow should accommodate small projects and gigs as well,and i think they will be deliverables,so can the escrow just store funds...hmmmmm

pub async fn resolve_dispute(
    pool: &PgPool,
    contract_id: Uuid,
    resolution: DisputeResolution,
) -> Result<(), String> {
    let mut transaction = pool.begin().await.map_err(|e| e.to_string())?;
    

    let contract = get_contract_with_escrow(&mut *transaction, contract_id).await?;
    let escrow_account = get_escrow_account(&mut *transaction, contract_id).await?;

    
    if !escrow_account.dispute {
        return Err("No event disputes".into());
    }

    // Fetch contract and escrow details
    let contract = sqlx::query_as!(
        Contract,
        r#"
        SELECT client_id, freelancer_id
        FROM contracts
        WHERE id = $1
        "#,
        contract_id
    )
    .fetch_one(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    let escrow_account = sqlx::query_as!(
        EscrowAccount,
        r#"
        SELECT id, amount, status, dispute
        FROM escrow_accounts
        WHERE contract_id = $1
        "#,
        contract_id
    )
    .fetch_one(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    if !escrow_account.dispute {
        return Err("No active dispute to resolve.".to_string());
    }

    // Calculate total transferred and validate
    let (total_transferred, transaction_types) = match resolution {
        DisputeResolution::FullReleaseToFreelancer(amount) => {
            if escrow_account.amount < amount {
                return Err("Insufficient funds in escrow account.".to_string());
            }
            (amount, vec![("Freelancer", amount)])
        }
        DisputeResolution::PartialReleaseToFreelancer(freelancer, client) => {
            let total = freelancer + client;
            if escrow_account.amount < total {
                return Err("Insufficient funds in escrow account.".to_string());
            }
            (total, vec![("Freelancer", freelancer), ("Client", client)])
        }
        DisputeResolution::RefundToClient(amount) => {
            if escrow_account.amount < amount {
                return Err("Insufficient funds in escrow account.".to_string());
            }
            (amount, vec![("Client", amount)])
        }
        DisputeResolution::CustomSplit { freelancer, client, platform } => {
            let total = freelancer + client + platform;
            if escrow_account.amount < total {
                return Err("Insufficient funds in escrow account.".to_string());
            }
            (total, vec![("Freelancer", freelancer), ("Client", client), ("Platform", platform)])
        }
    };

    // Perform transfers and log history
    for (recipient, amount) in  resolution.transfers() {
        match recipient {
            "Freelancer" => {
                transfer_to_freelancer(&mut *transaction, contract.freelancer_id, *amount).await?;
                record_payment_history(
                    &mut *transaction,
                    escrow_account.id,
                    *amount,
                    "Dispute Resolution Freelancer",
                    contract.freelancer_id,
                ).await?;
            }
            "Client" => {
                transfer_to_client(&mut *transaction, contract.client_id, *amount).await?;
                record_payment_history(
                    &mut *transaction,
                    escrow_account.id,
                    *amount,
                    "Dispute Resolution Client",
                    contract.client_id,
                ).await?;
            }
            "Platform" => {
                transfer_to_platform(&mut *transaction, *amount).await?;
                record_payment_history(
                    &mut *transaction,
                    escrow_account.id,
                    *amount,
                    "Dispute Resolution Platform",
                    get_platform_account_id(&mut *transaction).await?,
                ).await?;
            }
            _ => unreachable!(),
        }
    }

    // Update escrow balance and status
    sqlx::query!(
        r#"
        UPDATE escrow_accounts
        SET amount = amount - $1,
            dispute = FALSE,
            status = 'RESOLVED'
        WHERE contract_id = $2
        "#,
        total_transferred,
        contract_id
    )
    .execute(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    transaction.commit().await.map_err(|e| e.to_string())
}

// Helper functions
async fn transfer_to_freelancer(
    transaction: &mut PgTransaction,
    freelancer_id: i32,
    amount: Decimal,
) -> Result<(), String> {
    validate_account_exists(transaction, freelancer_id).await?;
    update_balance(transaction, freelancer_id, amount).await
}

async fn transfer_to_client(
    transaction: &mut PgTransaction,
    client_id: i32,
    amount: Decimal,
) -> Result<(), String> {
    validate_account_exists(transaction, client_id).await?;
    update_balance(transaction, client_id, amount).await
}

async fn transfer_to_platform(
    transaction: &mut PgTransaction,
    amount: Decimal,
) -> Result<(), String> {
    let platform_id = get_platform_account_id(transaction).await?;
    validate_account_exists(transaction, platform_id).await?;
    update_balance(transaction, platform_id, amount).await
}

async fn update_balance(
    transaction: &mut PgTransaction<'_>,
    account_id: i32,
    amount: Decimal,
) -> Result<(), String> {
    sqlx::query!(
        r#"
        UPDATE accounts
        SET balance = balance + $1
        WHERE id = $2
        "#,
        amount,
        account_id
    )
    .execute(transaction)
    .await
    .map_err(|e| e.to_string())?;
    Ok(())
}

async fn validate_account_exists(
    transaction: &mut PgTransaction,
    account_id: i32,
) -> Result<(), String> {
    let exists = sqlx::query!(
        "SELECT EXISTS(SELECT 1 FROM accounts WHERE id = $1)",
        account_id
    )
    .fetch_one(transaction)
    .await
    .map_err(|e| e.to_string())?
    .exists;

    if !exists {
        Err(format!("Account with ID {} does not exist.", account_id))
    } else {
        Ok(())
    }
}

async fn get_platform_account_id(transaction: &mut PgTransaction) -> Result<i32, String> {
    sqlx::query!(
        "SELECT id FROM accounts WHERE role = 'PLATFORM' LIMIT 1"
    )
    .fetch_one(transaction)
    .await
    .map(|row| row.id)
    .map_err(|e| e.to_string())
}

async fn record_payment_history(
    transaction: &mut PgTransaction,
    escrow_account_id: i32,
    amount: Decimal,
    transaction_type: &str,
    recipient_id: i32,
) -> Result<(), String> {
    sqlx::query!(
        r#"
        INSERT INTO payment_history (
            escrow_account_id, 
            amount, 
            transaction_type, 
            recipient_id
        ) 
        VALUES ($1, $2, $3, $4)
        "#,
        escrow_account_id,
        amount,
        transaction_type,
        recipient_id
    )
    .execute(transaction)
    .await
    .map_err(|e| e.to_string())?;
    Ok(())
}

async fn get_contract_with_escrow(
    transaction: &mut PgTransaction<'_>,
    contract_id: Uuid,
) -> Result<Contract, String> {
    sqlx::query_as!(
        Contract,
        r#"
        SELECT id, client_id, freelancer_id
        FROM contracts
        WHERE id = $1
        FOR SHARE
        "#,
        contract_id
    )
    .fetch_one(transaction)
    .await
    .map_err(|e| e.to_string())
}

async fn get_escrow_account(
    transaction: &mut PgTransaction<'_>,
    contract_id: Uuid,
) -> Result<EscrowAccount, String> {
    sqlx::query_as!(
        EscrowAccount,
        r#"
        SELECT id, contract_id, amount, status, dispute
        FROM escrow_accounts
        WHERE contract_id = $1
        FOR UPDATE
        "#,
        contract_id
    )
    .fetch_one(transaction)
    .await
    .map_err(|e| e.to_string())
}

// Types
#[derive(Debug)]
pub enum DisputeResolution {
    FullReleaseToFreelancer(Decimal),
    PartialRelease { freelancer: Decimal, client: Decimal },
    RefundToClient(Decimal),
    CustomSplit { freelancer: Decimal, client: Decimal, platform: Decimal },
}

impl DisputeResolution {
    fn transfers(&self) -> Vec<(Recipient, Decimal)> {
        match self {
            Self::FullReleaseToFreelancer(a) => vec![(Recipient::Freelancer, *a)],
            Self::PartialRelease { freelancer, client } => vec![
                (Recipient::Freelancer, *freelancer),
                (Recipient::Client, *client),
            ],
            Self::RefundToClient(a) => vec![(Recipient::Client, *a)],
            Self::CustomSplit { freelancer, client, platform } => vec![
                (Recipient::Freelancer, *freelancer),
                (Recipient::Client, *client),
                (Recipient::Platform, *platform),
            ],
        }
    }
}

#[derive(Debug)]
enum Recipient {
    Freelancer,
    Client,
    Platform,
}

// Constants
const PLATFORM_ACCOUNT_ID: i32 = 1;

// Error handling
#[derive(Debug, thiserror::Error)]
enum EscrowError {
    #[error("Database error:: {0}")]
    Database(#[from] sqlx::Error),
    #[error("Account does not exist: {0}")]
    AccountNotFound(i32),
    #[error("InsufficientFunds")]
    InsufficientFunds,
    #[error("InvalidState")]
    InvalidState,
}

pub async fn create_deliverable(
    pool: &PgPool,
    contract_id: Uuid, // Use UUID for contract_id
    description: String,
    amount: Decimal,
) -> Result<u32, String> {
    let result = sqlx::query!(
        r#"
        INSERT INTO deliverables (contract_id, description, amount, status)
        VALUES ($1, $2, $3, 'PENDING')
        RETURNING id
        "#,
        contract_id, // Pass UUID here
        description,
        amount
    )
    .fetch_one(pool)
    .await
    .map_err(|e| e.to_string())?;

    Ok(result.id as u32)
}

pub async fn mark_deliverable_as_completed(
    pool: &PgPool,
    deliverable_id: u32,
) -> Result<(), String> {
    sqlx::query!(
        r#"
        UPDATE deliverables
        SET status = 'COMPLETED', updated_at = NOW()
        WHERE id = $1 AND status = 'PENDING'
        "#,
        deliverable_id
    )
    .execute(pool)
    .await
    .map_err(|e| e.to_string())?;

    Ok(())
}

pub async fn authorize_release_for_deliverable(
    pool: &PgPool,
    deliverable_id: u32,
) -> Result<(), String> {
    sqlx::query!(
        r#"
        UPDATE deliverables
        SET status = 'AUTHORIZED', updated_at = NOW()
        WHERE id = $1 AND status = 'COMPLETED'
        "#,
        deliverable_id
    )
    .execute(pool)
    .await
    .map_err(|e| e.to_string())?;

    Ok(())
}

pub async fn release_funds_for_deliverable(
    pool: &PgPool,
    deliverable_id: u32,
) -> Result<(), String> {
    let mut transaction = pool.begin().await.map_err(|e| e.to_string())?;

    // Fetch deliverable details
    let deliverable = sqlx::query_as!(
        Deliverable,
        r#"
        SELECT id, contract_id, amount, status
        FROM deliverables
        WHERE id = $1
        "#,
        deliverable_id
    )
    .fetch_one(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    if deliverable.status != "AUTHORIZED" {
        return Err("Deliverable is not authorized for release.".to_string());
    }

    // Fetch contract and escrow details
    let contract = sqlx::query_as!(
        Contract,
        r#"
        SELECT client_id, freelancer_id
        FROM contracts
        WHERE id = $1
        "#,
        deliverable.contract_id
    )
    .fetch_one(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    let escrow_account = sqlx::query_as!(
        EscrowAccount,
        r#"
        SELECT id, amount
        FROM escrow_accounts
        WHERE contract_id = $1
        "#,
        deliverable.contract_id
    )
    .fetch_one(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    if escrow_account.amount < deliverable.amount {
        return Err("Insufficient funds in escrow account.".to_string());
    }

    // Deduct amount from escrow account
    let updated_escrow_balance = escrow_account.amount - deliverable.amount;
    sqlx::query!(
        r#"
        UPDATE escrow_accounts
        SET amount = $1
        WHERE contract_id = $2
        "#,
        updated_escrow_balance,
        deliverable.contract_id
    )
    .execute(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    // Transfer amount to freelancer's account
    update_balance(&mut *transaction, contract.freelancer_id, deliverable.amount).await?;

    // Record payment history
    record_payment_history(
        &mut *transaction,
        escrow_account.id,
        deliverable.amount,
        "Deliverable Release",
        contract.freelancer_id,
    ).await?;

    // Update deliverable status to RELEASED
    sqlx::query!(
        r#"
        UPDATE deliverables
        SET status = 'RELEASED', updated_at = NOW()
        WHERE id = $1
        "#,
        deliverable_id
    )
    .execute(&mut *transaction)
    .await
    .map_err(|e| e.to_string())?;

    transaction.commit().await.map_err(|e| e.to_string())
}

