use crate::models::{Proposal, ProposalStatus};
use sqlx::PgPool;
use chrono::{Utc, Duration};

/// Submit a new proposal while preventing duplicate submissions.
pub async fn submit_proposal(
    pool: &PgPool,
        freelancer_id: i32,
            job_id: i32,
                hourly_rate: Option<f64>,
                    project_rate: Option<String>,
                        description: String,
                        ) -> Result<Proposal, String> {
                            // Check if the freelancer has already submitted a proposal for this job
                                let existing_proposal = sqlx::query!(
                                        "SELECT id FROM proposals WHERE freelancer_id = $1 AND job_id = $2 AND deleted_at IS NULL",
                                                freelancer_id,
                                                        job_id
                                                            )
                                                                .fetch_optional(pool)
                                                                    .await
                                                                        .map_err(|e| format!("Database error: {}", e))?;

                                                                            if existing_proposal.is_some() {
                                                                                    return Err("You have already submitted a proposal for this job.".to_string());
                                                                                        }

                                                                                            let created_at = Utc::now().to_string();
                                                                                                let expires_at = (Utc::now() + Duration::days(30)).to_string(); // 30-day expiration

                                                                                                    // Insert new proposal
                                                                                                        let record = sqlx::query!(
                                                                                                                "INSERT INTO proposals (freelancer_id, job_id, hourly_rate, project_rate, description, created_at, status, expires_at) 
                                                                                                                         VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id",
                                                                                                                                 freelancer_id,
                                                                                                                                         job_id,
                                                                                                                                                 hourly_rate,
                                                                                                                                                         project_rate,
                                                                                                                                                                 description,
                                                                                                                                                                         created_at,
                                                                                                                                                                                 ProposalStatus::Submitted.to_string(),
                                                                                                                                                                                         expires_at
                                                                                                                                                                                             )
                                                                                                                                                                                                 .fetch_one(pool)
                                                                                                                                                                                                     .await
                                                                                                                                                                                                         .map_err(|e| format!("Failed to submit proposal: {}", e))?;

                                                                                                                                                                                                             Ok(Proposal {
                                                                                                                                                                                                                     id: record.id,
                                                                                                                                                                                                                             freelancer_id,
                                                                                                                                                                                                                                     job_id,
                                                                                                                                                                                                                                             hourly_rate,
                                                                                                                                                                                                                                                     project_rate,
                                                                                                                                                                                                                                                             description,
                                                                                                                                                                                                                                                                     created_at,
                                                                                                                                                                                                                                                                             status: ProposalStatus::Submitted,
                                                                                                                                                                                                                                                                                     expires_at: Some(expires_at),
                                                                                                                                                                                                                                                                                             deleted_at: None,
                                                                                                                                                                                                                                                                                                 })
                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                 /// Review and update the status of a proposal (Accepted/Rejected).
                                                                                                                                                                                                                                                                                                 pub async fn review_proposal(
                                                                                                                                                                                                                                                                                                     pool: &PgPool,
                                                                                                                                                                                                                                                                                                         proposal_id: i32,
                                                                                                                                                                                                                                                                                                             status: ProposalStatus,
                                                                                                                                                                                                                                                                                                             ) -> Result<Proposal, String> {
                                                                                                                                                                                                                                                                                                                 let record = sqlx::query!(
                                                                                                                                                                                                                                                                                                                         "UPDATE proposals SET status = $1 WHERE id = $2 AND deleted_at IS NULL RETURNING *",
                                                                                                                                                                                                                                                                                                                                 status.to_string(),
                                                                                                                                                                                                                                                                                                                                         proposal_id
                                                                                                                                                                                                                                                                                                                                             )
                                                                                                                                                                                                                                                                                                                                                 .fetch_one(pool)
                                                                                                                                                                                                                                                                                                                                                     .await
                                                                                                                                                                                                                                                                                                                                                         .map_err(|e| format!("Failed to review proposal: {}", e))?;

                                                                                                                                                                                                                                                                                                                                                             Ok(Proposal {
                                                                                                                                                                                                                                                                                                                                                                     id: record.id,
                                                                                                                                                                                                                                                                                                                                                                             freelancer_id: record.freelancer_id,
                                                                                                                                                                                                                                                                                                                                                                                     job_id: record.job_id,
                                                                                                                                                                                                                                                                                                                                                                                             hourly_rate: record.hourly_rate,
                                                                                                                                                                                                                                                                                                                                                                                                     project_rate: record.project_rate,
                                                                                                                                                                                                                                                                                                                                                                                                             description: record.description,
                                                                                                                                                                                                                                                                                                                                                                                                                     created_at: record.created_at,
                                                                                                                                                                                                                                                                                                                                                                                                                             status,
                                                                                                                                                                                                                                                                                                                                                                                                                                     expires_at: record.expires_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                             deleted_at: record.deleted_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                                 })
                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                 /// Retrieve proposals for a specific job with pagination.
                                                                                                                                                                                                                                                                                                                                                                                                                                                 pub async fn get_proposals_for_job(
                                                                                                                                                                                                                                                                                                                                                                                                                                                     pool: &PgPool,
                                                                                                                                                                                                                                                                                                                                                                                                                                                         job_id: i32,
                                                                                                                                                                                                                                                                                                                                                                                                                                                             limit: i64,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 offset: i64,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ) -> Result<Vec<Proposal>, String> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     let proposals = sqlx::query_as!(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Proposal,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "SELECT id, freelancer_id, job_id, hourly_rate, project_rate, description, created_at, status, expires_at, deleted_at 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             FROM proposals 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     WHERE job_id = $1 AND deleted_at IS NULL AND (expires_at IS NULL OR expires_at > NOW())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             LIMIT $2 OFFSET $3",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     job_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             limit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     offset
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             .fetch_all(pool)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 .await
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     .map_err(|e| format!("Database error: {}", e))?;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Ok(proposals)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         /// Retrieve a specific proposal by its ID.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         pub async fn get_proposal_by_id(pool: &PgPool, proposal_id: i32) -> Result<Proposal, String> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             sqlx::query_as!(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Proposal,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "SELECT id, freelancer_id, job_id, hourly_rate, project_rate, description, created_at, status, expires_at, deleted_at 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FROM proposals WHERE id = $1 AND deleted_at IS NULL",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             proposal_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     .fetch_one(pool)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         .await
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             .map_err(|e| format!("Error fetching proposal: {}", e))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             /// Allow freelancers to update their proposal before it is reviewed.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             pub async fn update_proposal(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 pool: &PgPool,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     proposal_id: i32,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         hourly_rate: Option<f64>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             project_rate: Option<String>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 description: String,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ) -> Result<Proposal, String> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     let record = sqlx::query!(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "UPDATE proposals 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SET hourly_rate = $1, project_rate = $2, description = $3, updated_at = NOW() 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             WHERE id = $4 AND deleted_at IS NULL 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     RETURNING *",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             hourly_rate,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     project_rate,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             description,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     proposal_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             .fetch_one(pool)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 .await
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     .map_err(|e| format!("Failed to update proposal: {}", e))?;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Ok(Proposal {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 id: record.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         freelancer_id: record.freelancer_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 job_id: record.job_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         hourly_rate: record.hourly_rate,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 project_rate: record.project_rate,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         description: record.description,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 created_at: record.created_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         status: record.status.parse().unwrap_or(ProposalStatus::Submitted),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 expires_at: record.expires_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         deleted_at: record.deleted_at,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             /// Soft delete a proposal (withdraw).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             pub async fn withdraw_proposal(pool: &PgPool, proposal_id: i32) -> Result<(), String> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 sqlx::query!(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "UPDATE proposals SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 proposal_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         .execute(pool)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             .await
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 .map_err(|e| format!("Failed to withdraw proposal: {}", e))?;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Ok(())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }