use actix_web::{web, HttpResponse, Responder};
use sqlx::PgPool;
use crate::models::task::{Task, NewTask};
use chrono::Utc;

// Create a new task
pub async fn create_task_handler(
    pool: web::Data<PgPool>,
    task: web::Json<NewTask>,
) -> Result<HttpResponse, ApiError> {
    let new_task = Task {
        id: 0, // Auto-generated by the database
        title: task.title.clone(),
        description: task.description.clone(),
        assigned_to: task.assigned_to,
        due_date: task.due_date,
        priority: task.priority.clone(),
        status: TaskStatus::ToDo, // Default status
        comments: vec![],
        files: vec![],
        created_at: Utc::now(),
        updated_at: Utc::now(),
    };

    let created_task = sqlx::query_as::<_, Task>(
        r#"
        INSERT INTO tasks (title, description, assigned_to, due_date, priority, status)
        VALUES ($1, $2, $3, $4, $5, 'ToDo')
        RETURNING *
        "#,
    )
    .bind(&new_task.title)
    .bind(&new_task.description)
    .bind(new_task.assigned_to.map(|id| id.to_string()))
    .bind(new_task.due_date)
    .bind(new_task.priority.to_string())
    .fetch_one(pool.as_ref())
    .await?;

    Ok(HttpResponse::Created().json(created_task))
}

// Get all tasks for a project
pub async fn get_tasks_for_project_handler(
    pool: web::Data<PgPool>,
    project_id: web::Path<u32>,
) -> Result<HttpResponse, ApiError> {
    let tasks = sqlx::query_as::<_, Task>(
        "SELECT * FROM tasks WHERE project_id = $1",
    )
    .bind(*project_id)
    .fetch_all(pool.as_ref())
    .await?;

    Ok(HttpResponse::Ok().json(tasks))
}

// Update a task
pub async fn update_task_handler(
    pool: web::Data<PgPool>,
    task_id: web::Path<u32>,
    task: web::Json<Task>,
) -> Result<HttpResponse, ApiError> {
    let updated_task = sqlx::query_as::<_, Task>(
        r#"
        UPDATE tasks
        SET title = COALESCE($2, title),
            description = COALESCE($3, description),
            assigned_to = COALESCE($4, assigned_to),
            due_date = COALESCE($5, due_date),
            priority = COALESCE($6, priority),
            status = COALESCE($7, status)
        WHERE id = $1
        RETURNING *
        "#,
    )
    .bind(*task_id)
    .bind(&task.title)
    .bind(&task.description)
    .bind(task.assigned_to.map(|id| id.to_string()))
    .bind(task.due_date)
    .bind(task.priority.to_string())
    .bind(task.status.to_string())
    .fetch_one(pool.as_ref())
    .await?;

    Ok(HttpResponse::Ok().json(updated_task))
}

// Delete a task
pub async fn delete_task_handler(
    pool: web::Data<PgPool>,
    task_id: web::Path<u32>,
) -> Result<HttpResponse, ApiError> {
    let rows_affected = sqlx::query(
        "DELETE FROM tasks WHERE id = $1",
    )
    .bind(*task_id)
    .execute(pool.as_ref())
    .await?
    .rows_affected();

    if rows_affected == 0 {
        return Err(ApiError::NotFound(format!("Task with ID {} not found", task_id)));
    }

    Ok(HttpResponse::NoContent().finish())
}

pub async fn add_comment_to_task_handler(
    pool: web::Data<PgPool>,
    task_id: web::Path<u32>,
    comment: web::Json<Comment>,
) -> Result<HttpResponse, ApiError> {
    let new_comment = sqlx::query_as::<_, Comment>(
        r#"
        INSERT INTO comments (task_id, author_id, content)
        VALUES ($1, $2, $3)
        RETURNING *
        "#,
    )
    .bind(*task_id)
    .bind(comment.author.id.to_string())
    .bind(&comment.content)
    .fetch_one(pool.as_ref())
    .await?;

    Ok(HttpResponse::Created().json(new_comment))
}

pub async fn add_file_to_task_handler(
    pool: web::Data<PgPool>,
    task_id: web::Path<u32>,
    file: web::Json<File>,
) -> Result<HttpResponse, ApiError> {
    let new_file = sqlx::query_as::<_, File>(
        r#"
        INSERT INTO files (task_id, filename, url, uploaded_by)
        VALUES ($1, $2, $3, $4)
        RETURNING *
        "#,
    )
    .bind(*task_id)
    .bind(&file.filename)
    .bind(&file.url)
    .bind(file.uploaded_by.to_string())
    .fetch_one(pool.as_ref())
    .await?;

    Ok(HttpResponse::Created().json(new_file))
}

pub async fn mark_task_as_completed_handler(
    pool: web::Data<PgPool>,
    task_id: web::Path<u32>,
) -> Result<HttpResponse, ApiError> {
    let rows_affected = sqlx::query(
        r#"
        UPDATE tasks
        SET status = 'Completed', updated_at = NOW()
        WHERE id = $1 AND status != 'Completed'
        "#,
    )
    .bind(*task_id)
    .execute(pool.as_ref())
    .await?
    .rows_affected();

    if rows_affected == 0 {
        return Err(ApiError::NotFound(format!("Task with ID {} not found or already completed", task_id)));
    }

    Ok(HttpResponse::Ok().body("Task marked as completed"))
}