use serde::{Serialize, Deserialize};
use chrono::DateTime;
use uuid::Uuid;

/// Represents data displayed on the admin dashboard.
#[derive(Debug, Serialize)]
pub struct AdminDashboardData {
    pub jobs_posted: usize,
    pub clients_count: usize,
    pub freelancers_count: usize,
    pub active_projects_count: usize,
    pub membership_tiers: Vec<String>,
    pub notifications: Vec<String>,
}

/// Represents job statistics for the admin panel.
#[derive(Debug, Serialize)]
pub struct JobStatistics {
    pub total_jobs_posted: usize,
    pub recent_jobs: Vec<Job>,
    pub jobs_by_category: Vec<JobCategoryCount>,
}

/// Represents a single job.
#[derive(Debug, Serialize)]
pub struct Job {
    pub id: i32,
    pub title: String,
    pub description: String,
    pub category: String,
    pub created_at: DateTime<Utc>,
}

/// Represents job counts grouped by category.
#[derive(Debug, Serialize)]
pub struct JobCategoryCount {
    pub category_name: String,
    pub count: usize,
}

/// Represents a simplified user profile viewable by admins.
#[derive(Debug, Serialize)]
pub struct UserProfile {
    pub id: i32,
    pub username: String,
    pub email: String,
    pub role: UserRole,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Represents detailed project information viewable by admins.
#[derive(Debug, Serialize)]
pub struct ProjectDetails {
    pub id: i32,
    pub name: String,
    pub description: String,
    pub status: String,
    pub client_username: String,
    pub freelancers: Vec<String>,
    pub deadlines: Vec<DateTime<Utc>>,
    pub progress: f32,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Represents an overview of active projects.
#[derive(Debug, Serialize)]
pub struct ProjectOverview {
    pub id: i32,
    pub name: String,
    pub status: String,
    pub client_username: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Represents revenue statistics grouped by membership tier.
#[derive(Debug, Serialize)]
pub struct RevenueByTier {
    pub tier_name: String,
    pub total_revenue: f64,
    pub period: String, // e.g., "Monthly", "Yearly"
}

/// Represents user growth statistics over time.
#[derive(Debug, Serialize)]
pub struct UserGrowthReport {
    pub total_users: usize,
    pub new_users: Vec<NewUser>,
    pub active_users_over_time: Vec<ActiveUsersOverTime>,
}

/// Represents newly registered users.
#[derive(Debug, Serialize)]
pub struct NewUser {
    pub user_id: i32,
    pub username: String,
    pub registration_date: DateTime<Utc>,
}

/// Represents active user counts over time.
#[derive(Debug, Serialize)]
pub struct ActiveUsersOverTime {
    pub date: DateTime<Utc>,
    pub active_users: usize,
}

/// Represents membership tier statistics.
#[derive(Debug, Serialize)]
pub struct MembershipStatistics {
    pub tier_name: String,
    pub user_count: usize,
    pub revenue: f64,
}

/// Represents a system notification.
#[derive(Debug, Serialize, Deserialize)]
pub struct SystemNotification {
    pub id: i32,
    pub message: String,
    pub notification_type: String,
    pub is_read: bool,
    pub created_at: DateTime<Utc>,
}

/// Represents a user notification.
#[derive(Debug, Serialize, Deserialize)]
pub struct UserNotification {
    pub id: i32,
    pub user_id: i32,
    pub message: String,
    pub notification_type: String,
    pub is_read: bool,
    pub created_at: DateTime<Utc>,
}

/// Represents an admin activity log entry.
#[derive(Debug, Serialize, Deserialize)]
pub struct AdminActivityLog {
    pub id: i32,
    pub admin_id: i32,
    pub action: String,
    pub details: Option<String>,
    pub timestamp: DateTime<Utc>,
}

/// Represents revenue reports generated by the admin.
#[derive(Debug, Serialize)]
pub struct RevenueReport {
    pub total_revenue: f64,
    pub revenue_by_tier: Vec<RevenueByTier>,
    pub revenue_over_time: Vec<RevenueOverTime>,
}

/// Represents revenue over time (e.g., monthly or yearly).
#[derive(Debug, Serialize)]
pub struct RevenueOverTime {
    pub date: DateTime<Utc>,
    pub revenue: f64,
}

/// Represents exported user data.
#[derive(Debug, Serialize)]
pub struct UserDataExport {
    pub user_id: i32,
    pub username: String,
    pub email: String,
    pub registration_date: DateTime<Utc>,
    // Add other relevant fields as needed
}

/// Represents a request to generate custom reports.
#[derive(Debug, Deserialize)]
pub struct ReportRequest {
    pub report_type: String, // e.g., "revenue", "user_growth"
    pub period: Option<String>, // e.g., "Monthly", "Yearly"
}

/// Represents a response containing system notifications.
#[derive(Debug, Serialize)]
pub struct SystemNotificationResponse {
    pub notifications: Vec<SystemNotification>,
}

/// Represents a response containing user notifications.
#[derive(Debug, Serialize)]
pub struct UserNotificationResponse {
    pub notifications: Vec<UserNotification>,
}

/// Represents a query for filtering notifications.
#[derive(Debug, Deserialize)]
pub struct NotificationQuery {
    pub notification_type: Option<String>,
    pub is_read: Option<bool>,
}

/// Represents a query for filtering user notifications.
#[derive(Debug, Deserialize)]
pub struct UserNotificationQuery {
    pub user_id: Option<i32>,
    pub notification_type: Option<String>,
    pub is_read: Option<bool>,
}

/// Represents a request to create or update a membership tier.
#[derive(Debug, Deserialize, Validate)]
pub struct CreateMembershipTierInput {
    #[validate(length(min = 1))]
    pub name: String,
    #[validate(range(min = 0.0))]
    pub price: f64,
    pub features: serde_json::Value,
}

/// Represents a membership tier in the database.
#[derive(Debug, Serialize, Deserialize)]
pub struct MembershipTier {
    pub id: i32,
    pub name: String,
    pub price: f64,
    pub features: serde_json::Value,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Represents user roles with associated privileges.
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone, Copy)]
pub enum UserRole {
    Admin,
    Client,
    Freelancer,
}

/// Represents subscription statuses for users.
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone, Copy)]
pub enum SubscriptionStatus {
    Active,
    Inactive,
    Canceled,
}

/// Represents user privileges based on their role.
#[derive(Debug, Serialize, Deserialize)]
pub struct Privileges {
    pub can_create_users: bool,
    pub can_edit_users: bool,
    pub can_delete_users: bool,
    pub can_view_reports: bool,
    pub can_manage_projects: bool,
    pub can_view_clients: bool,
    pub can_view_freelancers: bool,
    pub can_create_projects: bool,
    pub can_edit_projects: bool,
    pub can_delete_projects: bool,
    // Add other privileges as necessary
}

impl Privileges {
    /// Returns default privileges for a given user role.
    pub fn from_role(role: UserRole) -> Self {
        match role {
            UserRole::Admin => Privileges {
                can_create_users: true,
                can_edit_users: true,
                can_delete_users: true,
                can_view_reports: true,
                can_manage_projects: true,
                can_view_clients: true,
                can_view_freelancers: true,
                can_create_projects: true,
                can_edit_projects: true,
                can_delete_projects: true,
            },
            UserRole::Client => Privileges {
                can_create_users: false,
                can_edit_users: false,
                can_delete_users: false,
                can_view_reports: false,
                can_manage_projects: true,
                can_view_clients: false,
                can_view_freelancers: true,
                can_create_projects: true,
                can_edit_projects: true,
                can_delete_projects: false,
            },
            UserRole::Freelancer => Privileges {
                can_create_users: false,
                can_edit_users: false,
                can_delete_users: false,
                can_view_reports: false,
                can_manage_projects: false,
                can_view_clients: true,
                can_view_freelancers: false,
                can_create_projects: false,
                can_edit_projects: false,
                can_delete_projects: false,
            },
        }
    }
}

/// Represents a dispute escalation level.
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone, Copy)]
pub enum DisputeLevel {
    InitialReview,
    Mediation,
    Arbitration,
    Resolved,
}

/// Represents a dispute resolution outcome.
#[derive(Debug, Serialize, Deserialize)]
pub enum DisputeResolution {
    FullReleaseToFreelancer(f64),
    PartialReleaseToFreelancer { freelancer: f64, client: f64 },
    RefundToClient(f64),
    CustomSplit { freelancer: f64, client: f64, platform: f64 },
}

/// Represents a user's account type.
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone, Copy)]
pub enum AccountType {
    Standard,
    Premium,
}

/// Represents a user's location.
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone, Copy)]
pub struct Location {
    pub city: String,
    pub country: String,
}

/// Represents a user in the system.
#[derive(Debug, Serialize, Deserialize)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub email: String,
    pub password_hash: String,
    pub membership_tier: MembershipTier,
    pub account_type: AccountType,
    pub role: UserRole,
    pub location: Location,
    pub subscription_status: SubscriptionStatus,
    pub subscription_end_date: Option<DateTime<Utc>>,
    pub stripe_customer_id: Option<Uuid>,
    pub privileges: Privileges,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}