use chrono::DateTime;
use serde::{Serialize, Deserialize};
use crate::models::user::User;
use crate::models::task::Task;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct TimeEntry {
    pub id: u32,
    pub user_id: u32,
    pub task_id: u32,
    pub start_time: DateTime<chrono::Utc>,
    pub end_time: DateTime<chrono::Utc>,
}

impl TimeEntry {
    pub fn new(user_id: u32, task_id: u32, start_time: DateTime<chrono::Utc>, end_time: DateTime<chrono::Utc>) -> Self {
        Self {
            id: 0, // Auto-generated by the database
            user_id,
            task_id,
            start_time,
            end_time,
        }
    }

    pub fn duration(&self) -> chrono::Duration {
        self.end_time.signed_duration_since(self.start_time)
    }
}